import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Check, Clipboard, Eye, Search, Sparkles, X } from 'lucide-react';
import { promptGalleryService } from '@/services/promptGalleryService';
import type { AIPrompt } from '@/types/promptGallery';
import { PageHeader } from '@/components/common/PageHeader';
import { Card } from '@/components/common/Card';
import { Button } from '@/components/ui/button';
import { LoadingState } from '@/components/common/LoadingState';
import { Alert } from '@/components/ui/Alert';

export function PromptGalleryPage() {
  const [search, setSearch] = useState(''); const [categoryId, setCategoryId] = useState(''); const [aiTool, setAiTool] = useState(''); const [selected, setSelected] = useState<AIPrompt | null>(null); const [copied, setCopied] = useState<string | null>(null);
  const categories = useQuery({ queryKey: ['prompt-categories'], queryFn: promptGalleryService.categories });
  const tools = useQuery({ queryKey: ['prompt-tools'], queryFn: promptGalleryService.tools });
  const prompts = useQuery({ queryKey: ['prompt-gallery', search, categoryId, aiTool], queryFn: () => promptGalleryService.list({ search: search || undefined, categoryId: categoryId || undefined, aiTool: aiTool || undefined }) });
  const copy = async (prompt: AIPrompt) => { await navigator.clipboard.writeText(prompt.content); setCopied(prompt.id); window.setTimeout(() => setCopied(null), 2200); };
  return <main className="page-container"><PageHeader eyebrow="Marketing tools" title="AI Prompt Gallery" description="Find ready-made AI prompts to create product photos, advertisements, captions, and marketing ideas." />
    <Card className="mt-6"><div className="grid gap-3 lg:grid-cols-[1fr_220px_220px]"><label className="relative"><Search className="absolute left-3 top-3.5 size-4 text-slate-400" /><input className="control w-full pl-10" value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search prompts" aria-label="Search prompts" /></label><select className="control" value={categoryId} onChange={(e) => setCategoryId(e.target.value)} aria-label="Filter by category"><option value="">All categories</option>{categories.data?.map((c) => <option key={c.id} value={c.id}>{c.icon} {c.name}</option>)}</select><select className="control" value={aiTool} onChange={(e) => setAiTool(e.target.value)} aria-label="Filter by AI tool"><option value="">All AI tools</option>{tools.data?.map((tool) => <option key={tool}>{tool}</option>)}</select></div></Card>
    {copied && <Alert className="mt-4" tone="success"><Check className="size-4" /> Prompt copied successfully</Alert>}
    {prompts.isLoading ? <LoadingState label="Loading prompts" /> : prompts.isError ? <Alert className="mt-4" tone="error">Could not load the prompt gallery.</Alert> : prompts.data?.length === 0 ? <Card className="mt-5 text-center"><Sparkles className="mx-auto size-8 text-violet-500" /><p className="mt-3 font-semibold">No prompts match your search</p><p className="mt-1 text-sm text-slate-500">Try another word or clear a filter.</p></Card> : <div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{prompts.data?.map((prompt) => <Card key={prompt.id} className="flex flex-col"><div className="flex items-start justify-between gap-3"><span className="rounded-full bg-violet-50 px-3 py-1 text-xs font-semibold text-violet-700 dark:bg-violet-500/10 dark:text-violet-300">{prompt.category.icon} {prompt.category.name}</span><span className="text-right text-xs font-medium text-slate-500">{prompt.aiTools.join(' + ')}</span></div>{prompt.exampleImageUrl && <button type="button" className="mt-4 flex h-52 w-full items-center justify-center overflow-hidden rounded-xl bg-slate-100 dark:bg-slate-950" onClick={() => setSelected(prompt)} aria-label={`View full image for ${prompt.title}`}><img src={prompt.exampleImageUrl} alt={`Example for ${prompt.title}`} className="max-h-full max-w-full object-contain" /></button>}<h2 className="mt-4 flex-1 text-lg font-bold">{prompt.title}</h2><div className="mt-5 flex gap-2"><Button className="flex-1" variant="outline" onClick={() => setSelected(prompt)}><Eye className="size-4" />View Prompt</Button><Button onClick={() => copy(prompt)} aria-label={`Copy ${prompt.title}`}><Clipboard className="size-4" />Copy</Button></div></Card>)}</div>}
    {selected && <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/60 p-4" role="dialog" aria-modal="true" aria-labelledby="prompt-title"><div className="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-2xl bg-white p-5 shadow-2xl dark:bg-slate-900 sm:p-7"><div className="flex items-start justify-between gap-4"><div><p className="text-sm font-semibold text-violet-600">{selected.category.icon} {selected.category.name} · {selected.aiTools.join(' + ')}</p><h2 id="prompt-title" className="mt-1 text-2xl font-bold">{selected.title}</h2></div><button onClick={() => setSelected(null)} className="rounded-lg p-2 hover:bg-slate-100 dark:hover:bg-slate-800" aria-label="Close"><X className="size-5" /></button></div>{selected.exampleImageUrl && <a href={selected.exampleImageUrl} target="_blank" rel="noreferrer" className="mt-5 flex max-h-[60vh] w-full items-center justify-center overflow-hidden rounded-xl bg-slate-100 dark:bg-slate-950" title="Open full-size image"><img src={selected.exampleImageUrl} alt={`Example for ${selected.title}`} className="max-h-[60vh] max-w-full object-contain" /></a>}<h3 className="mt-6 text-sm font-bold uppercase tracking-wide text-slate-500">Prompt content</h3><pre className="mt-2 whitespace-pre-wrap rounded-xl bg-slate-100 p-4 font-sans text-sm leading-6 dark:bg-slate-950">{selected.content}</pre><Button className="mt-5 w-full" onClick={() => copy(selected)}><Clipboard className="size-4" />Copy Prompt</Button></div></div>}
  </main>;
}
