import type { Language } from '@/hooks/useLanguage';

export interface BusinessQuizQuestion {
  question: string;
  choices: string[];
  answer: number;
  note: string;
}

const questionBank: Record<Language, BusinessQuizQuestion[]> = {
  en: [
    { question: 'Which products should you review first?', choices: ['Low-stock products', 'Every product equally', 'Only new products'], answer: 0, note: 'Low-stock products can cause missed sales if they are not replenished.' },
    { question: 'Which invoices count toward Climbio paid revenue?', choices: ['Draft invoices', 'Sent invoices', 'Paid invoices'], answer: 2, note: 'Revenue metrics use invoices confirmed as Paid.' },
    { question: 'What appears in the public catalog?', choices: ['Every saved product', 'Active and publicly visible products', 'Out-of-stock products only'], answer: 1, note: 'Only active products enabled for public visibility appear to customers.' },
    { question: 'What is gross profit?', choices: ['Revenue minus cost of goods sold', 'Cash in the bank', 'Revenue before any costs'], answer: 0, note: 'Gross profit shows what remains after subtracting the direct cost of sold products.' },
    { question: 'Why can a profitable business still run out of cash?', choices: ['Profit and cash timing are different', 'Profit always equals cash', 'Sales never affect cash'], answer: 0, note: 'Credit sales, inventory purchases, and payment timing can create a cash shortage despite profit.' },
    { question: 'What does a reorder point tell you?', choices: ['When to replenish stock', 'When to raise every price', 'When to close the shop'], answer: 0, note: 'A reorder point helps you replenish before stock reaches zero.' },
    { question: 'What can high inventory turnover indicate?', choices: ['Products are selling efficiently', 'No products are sold', 'Prices are always too low'], answer: 0, note: 'Higher turnover often means stock sells and is replenished efficiently, though context matters.' },
    { question: 'Which usually costs less?', choices: ['Keeping a satisfied customer', 'Finding a new customer every time', 'Ignoring existing customers'], answer: 0, note: 'Retention commonly costs less than repeatedly acquiring new customers.' },
    { question: 'What is the break-even point?', choices: ['Where revenue equals total costs', 'The highest possible profit', 'The day stock arrives'], answer: 0, note: 'At break-even, the business covers its costs but has not yet earned profit.' },
    { question: 'What is a risk of frequent large discounts?', choices: ['Lower profit margin', 'Guaranteed loyalty', 'Higher margin on every sale'], answer: 0, note: 'Discounts can increase volume but reduce the profit earned per item.' },
    { question: 'Why avoid depending on only one supplier?', choices: ['To reduce supply disruption risk', 'To make ordering impossible', 'To remove price comparisons'], answer: 0, note: 'Alternative suppliers reduce the impact of delays, shortages, or price changes.' },
    { question: 'What is the best first response to a customer complaint?', choices: ['Listen and clarify the problem', 'Argue immediately', 'Delete the message'], answer: 0, note: 'Listening carefully helps identify a fair and effective solution.' },
    { question: 'Which goal is most useful?', choices: ['Increase paid sales by 10% in 60 days', 'Do better someday', 'Become perfect immediately'], answer: 0, note: 'Useful goals are specific, measurable, achievable, relevant, and time-bound.' },
    { question: 'What should you compare when sales decline?', choices: ['Periods, products, stock, and customers', 'Only the shop logo', 'Nothing until year-end'], answer: 0, note: 'Comparing multiple business signals helps identify evidence-supported causes.' },
    { question: 'What can you do with slow-moving stock?', choices: ['Review price, promotion, or bundle options', 'Keep ordering more automatically', 'Hide it from all records'], answer: 0, note: 'A targeted promotion or bundle may release cash tied up in slow stock.' },
    { question: 'Why keep an emergency business reserve?', choices: ['To handle unexpected costs or weak sales', 'To avoid all bookkeeping', 'To guarantee profit'], answer: 0, note: 'A reserve gives the business time to respond to disruptions.' },
    { question: 'Why separate personal and business money?', choices: ['To understand true business performance', 'To create more confusion', 'To remove the need for records'], answer: 0, note: 'Separate accounts make cash flow, costs, and profit easier to measure.' },
    { question: 'Why update invoice status accurately?', choices: ['To keep revenue and payment records reliable', 'To change product names', 'To increase stock automatically in every case'], answer: 0, note: 'Accurate statuses distinguish pending sales from payments actually received.' },
    { question: 'What should influence a selling price?', choices: ['Cost, customer value, market, and target margin', 'Cost alone in every situation', 'A random number'], answer: 0, note: 'Good pricing balances costs, perceived value, competition, and desired margin.' },
    { question: 'What should you compare between suppliers?', choices: ['Price, quality, reliability, and terms', 'Logo color only', 'Social follower count only'], answer: 0, note: 'The cheapest supplier may not be best if quality or delivery is unreliable.' },
    { question: 'What does marketing ROI help measure?', choices: ['Return produced by marketing spending', 'Product weight', 'Employee attendance'], answer: 0, note: 'Marketing ROI compares the value generated with the campaign cost.' },
    { question: 'Why are repeat customers valuable?', choices: ['They can provide steadier revenue and referrals', 'They never need service', 'They always buy everything'], answer: 0, note: 'Repeat customers can improve predictability and recommend the shop to others.' },
    { question: 'Why perform a physical stock count?', choices: ['To compare real stock with system records', 'To change currency', 'To create customer accounts'], answer: 0, note: 'Physical counts reveal damage, loss, and recording errors.' },
    { question: 'What is a good data-backup practice?', choices: ['Keep secure, tested backups', 'Use only one untested copy', 'Share passwords with everyone'], answer: 0, note: 'A backup is useful only when it is protected and can be restored.' },
    { question: 'What should you do with a suspicious login link?', choices: ['Do not open it; verify through the official site', 'Enter your password quickly', 'Forward it to customers'], answer: 0, note: 'Phishing links can steal credentials; use the known official address instead.' },
    { question: 'How should you prepare for seasonal demand?', choices: ['Review past sales and supplier lead times', 'Order randomly', 'Ignore stock levels'], answer: 0, note: 'Historical demand and delivery time support safer seasonal purchasing.' },
    { question: 'What is helpful upselling?', choices: ['Suggesting a relevant higher-value option', 'Forcing unwanted products', 'Hiding the original price'], answer: 0, note: 'Ethical upselling helps the customer choose an option that better fits their need.' },
    { question: 'How should customer feedback be used?', choices: ['Look for repeated themes and prioritize improvements', 'Follow every comment blindly', 'Never record it'], answer: 0, note: 'Repeated feedback patterns are stronger evidence than a single isolated comment.' },
    { question: 'Which is usually a fixed cost?', choices: ['Monthly shop rent', 'Packaging per item sold', 'Product purchase cost'], answer: 0, note: 'Fixed costs generally remain similar even when sales volume changes.' },
    { question: 'What is the difference between revenue and profit?', choices: ['Profit is revenue remaining after costs', 'They are always identical', 'Revenue is always smaller than profit'], answer: 0, note: 'Revenue is sales income; profit is what remains after relevant costs.' },
  ],
  my: [
    { question: 'မည်သည့်ကုန်ပစ္စည်းများကို အရင်ဆုံး စစ်ဆေးသင့်သလဲ?', choices: ['စတော့နည်းသောပစ္စည်းများ', 'ပစ္စည်းအားလုံးကို တူညီစွာ', 'အသစ်ထည့်ထားသောပစ္စည်းများသာ'], answer: 0, note: 'စတော့နည်းသောပစ္စည်းများကို အချိန်မီမဖြည့်ပါက အရောင်းလွတ်သွားနိုင်ပါသည်။' },
    { question: 'Climbio ဝင်ငွေတွင် မည်သည့်ဘောက်ချာများကို ထည့်တွက်သလဲ?', choices: ['မူကြမ်းဘောက်ချာ', 'ပို့ပြီးဘောက်ချာ', 'ပေးချေပြီးဘောက်ချာ'], answer: 2, note: 'ဝင်ငွေကိန်းဂဏန်းများသည် Paid အဖြစ် အတည်ပြုထားသောဘောက်ချာများကို သုံးပါသည်။' },
    { question: 'အများမြင်ကုန်ပစ္စည်းစာရင်းတွင် မည်သည့်ပစ္စည်းများ ပေါ်သလဲ?', choices: ['သိမ်းထားသမျှပစ္စည်းအားလုံး', 'အသုံးပြုနေပြီး အများမြင်ခွင့်ဖွင့်ထားသောပစ္စည်းများ', 'စတော့ကုန်ပစ္စည်းများသာ'], answer: 1, note: 'အသုံးပြုနေပြီး Public visibility ဖွင့်ထားသောပစ္စည်းများသာ ဝယ်ယူသူများမြင်နိုင်ပါသည်။' },
    { question: 'အကြမ်းအမြတ်ဆိုသည်မှာ အဘယ်နည်း?', choices: ['ဝင်ငွေမှ ရောင်းကုန်တိုက်ရိုက်ကုန်ကျစရိတ် နုတ်ထားခြင်း', 'ဘဏ်ထဲရှိငွေအားလုံး', 'ကုန်ကျစရိတ်မနုတ်မီ ဝင်ငွေ'], answer: 0, note: 'အကြမ်းအမြတ်သည် ရောင်းချပြီးပစ္စည်း၏ တိုက်ရိုက်ကုန်ကျစရိတ်ကို နုတ်ပြီး ကျန်သည့်ပမာဏဖြစ်သည်။' },
    { question: 'အမြတ်ရှိသော်လည်း လက်ငင်းငွေ ဘာကြောင့်ကုန်နိုင်သလဲ?', choices: ['အမြတ်နှင့် ငွေဝင်ထွက်အချိန် မတူသောကြောင့်', 'အမြတ်သည် လက်ငင်းငွေနှင့် အမြဲတူသည်', 'အရောင်းသည် ငွေသားကို မသက်ရောက်ပါ'], answer: 0, note: 'အကြွေးရောင်းခြင်း၊ စတော့ဝယ်ခြင်းနှင့် ငွေပေးချေချိန်တို့ကြောင့် အမြတ်ရှိသော်လည်း ငွေကြပ်နိုင်ပါသည်။' },
    { question: 'Reorder point က ဘာကိုပြသသလဲ?', choices: ['စတော့ပြန်ဖြည့်ရမည့်အချိန်', 'ဈေးအားလုံးတင်ရမည့်အချိန်', 'ဆိုင်ပိတ်ရမည့်အချိန်'], answer: 0, note: 'Reorder point သည် စတော့မကုန်မီ ပြန်လည်မှာယူနိုင်ရန် ကူညီပါသည်။' },
    { question: 'စတော့လည်ပတ်နှုန်း မြင့်ခြင်းက ဘာကိုပြနိုင်သလဲ?', choices: ['ပစ္စည်းများ ထိရောက်စွာ ရောင်းထွက်နေခြင်း', 'ပစ္စည်းလုံးဝ မရောင်းရခြင်း', 'ဈေးအမြဲနိမ့်လွန်းခြင်း'], answer: 0, note: 'အခြေအနေပေါ်မူတည်သော်လည်း လည်ပတ်နှုန်းမြင့်ခြင်းသည် စတော့ရောင်းထွက်ပြီး ထိရောက်စွာ ပြန်ဖြည့်နေခြင်းကို ပြနိုင်သည်။' },
    { question: 'မည်သည့်အရာက ပုံမှန်အားဖြင့် ကုန်ကျစရိတ်နည်းသလဲ?', choices: ['ကျေနပ်ပြီးသားဝယ်ယူသူကို ထိန်းသိမ်းခြင်း', 'အကြိမ်တိုင်း ဝယ်ယူသူအသစ်ရှာခြင်း', 'လက်ရှိဝယ်ယူသူကို လျစ်လျူရှုခြင်း'], answer: 0, note: 'လက်ရှိဝယ်ယူသူကို ထိန်းသိမ်းခြင်းသည် ဝယ်ယူသူအသစ်ကို အမြဲရှာခြင်းထက် ကုန်ကျစရိတ်နည်းလေ့ရှိသည်။' },
    { question: 'Break-even point ဆိုသည်မှာ အဘယ်နည်း?', choices: ['ဝင်ငွေနှင့် စုစုပေါင်းကုန်ကျစရိတ် တူညီသည့်အမှတ်', 'ရနိုင်သမျှ အမြတ်အများဆုံး', 'စတော့ရောက်သည့်နေ့'], answer: 0, note: 'Break-even တွင် ကုန်ကျစရိတ်အားလုံး ကာမိသော်လည်း အမြတ်မရသေးပါ။' },
    { question: 'လျှော့ဈေးကြီးကြီး မကြာခဏပေးခြင်း၏ အန္တရာယ်က ဘာလဲ?', choices: ['အမြတ်နှုန်း လျော့နည်းခြင်း', 'ဝယ်ယူသူ အမြဲတမ်းသစ္စာရှိခြင်း', 'ရောင်းတိုင်း အမြတ်ပိုရခြင်း'], answer: 0, note: 'လျှော့ဈေးက အရောင်းအရေအတွက်တိုးစေနိုင်သော်လည်း ပစ္စည်းတစ်ခုချင်းအမြတ်ကို လျော့စေနိုင်သည်။' },
    { question: 'ကုန်ပစ္စည်းပေးသွင်းသူတစ်ဦးတည်းကို မမှီခိုသင့်သည့်အကြောင်းက ဘာလဲ?', choices: ['ပစ္စည်းပြတ်လပ်မှုအန္တရာယ် လျှော့ချရန်', 'မှာယူမှုကို ပိုခက်စေရန်', 'ဈေးနှိုင်းယှဉ်မှု မလုပ်ရန်'], answer: 0, note: 'အခြားပေးသွင်းသူရှိခြင်းက ပို့ဆောင်မှုနှောင့်နှေးခြင်း၊ ပြတ်လပ်ခြင်းနှင့် ဈေးပြောင်းခြင်းကို ခံနိုင်ရည်ရှိစေသည်။' },
    { question: 'ဝယ်ယူသူတိုင်ကြားချက်ကို ပထမဆုံး ဘယ်လိုတုံ့ပြန်သင့်သလဲ?', choices: ['နားထောင်ပြီး ပြဿနာကို ရှင်းလင်းမေးမြန်းရန်', 'ချက်ချင်းငြင်းခုံရန်', 'စာကိုဖျက်ရန်'], answer: 0, note: 'သေချာနားထောင်ခြင်းက မျှတပြီး ထိရောက်သောဖြေရှင်းချက် ရှာနိုင်စေသည်။' },
    { question: 'မည်သည့်ရည်မှန်းချက်က ပိုအသုံးဝင်သလဲ?', choices: ['ရက် ၆၀ အတွင်း Paid အရောင်း ၁၀% တိုးရန်', 'တစ်နေ့နေ့ ပိုကောင်းလာရန်', 'ချက်ချင်း ပြည့်စုံသွားရန်'], answer: 0, note: 'ကောင်းသောရည်မှန်းချက်သည် တိကျ၊ တိုင်းတာနိုင်၊ လက်တွေ့ဖြစ်နိုင်ပြီး အချိန်သတ်မှတ်ထားရမည်။' },
    { question: 'အရောင်းကျဆင်းလျှင် ဘာတွေကို နှိုင်းယှဉ်သင့်သလဲ?', choices: ['ကာလ၊ ပစ္စည်း၊ စတော့နှင့် ဝယ်ယူသူ', 'ဆိုင်လိုဂိုတစ်ခုတည်း', 'နှစ်ကုန်အထိ ဘာမှမလုပ်ရန်'], answer: 0, note: 'လုပ်ငန်းအချက်ပြများစွာကို နှိုင်းယှဉ်ခြင်းက အထောက်အထားရှိသောအကြောင်းရင်းကို ရှာနိုင်စေသည်။' },
    { question: 'ရောင်းနှေးသောစတော့ကို ဘယ်လိုစီမံနိုင်သလဲ?', choices: ['ဈေး၊ Promotion သို့မဟုတ် အတွဲလိုက်ရောင်းခြင်း ပြန်သုံးသပ်ရန်', 'အလိုအလျောက် ထပ်မှာရန်', 'မှတ်တမ်းအားလုံးမှ ဖျောက်ရန်'], answer: 0, note: 'ရည်ရွယ်ချက်ရှိသော Promotion သို့မဟုတ် အတွဲလိုက်ရောင်းခြင်းက ပိတ်မိနေသောငွေကို ပြန်လည်ရရှိစေနိုင်သည်။' },
    { question: 'လုပ်ငန်းအရေးပေါ်ငွေ ဘာကြောင့်ထားသင့်သလဲ?', choices: ['မမျှော်လင့်သောကုန်ကျစရိတ် သို့မဟုတ် အရောင်းကျဆင်းမှုကို ဖြေရှင်းရန်', 'စာရင်းမမှတ်ရန်', 'အမြတ်အာမခံရန်'], answer: 0, note: 'အရေးပေါ်ငွေက ပြဿနာကြုံချိန်တွင် လုပ်ငန်းကို အချိန်ရစေပါသည်။' },
    { question: 'ကိုယ်ပိုင်ငွေနှင့် လုပ်ငန်းငွေကို ဘာကြောင့်ခွဲထားသင့်သလဲ?', choices: ['လုပ်ငန်းစွမ်းဆောင်ရည်အစစ်ကို သိရန်', 'ပိုမိုရှုပ်ထွေးစေရန်', 'မှတ်တမ်းမလိုအပ်စေရန်'], answer: 0, note: 'ခွဲထားခြင်းက ငွေဝင်ထွက်၊ ကုန်ကျစရိတ်နှင့် အမြတ်ကို တိကျစွာတိုင်းတာနိုင်စေသည်။' },
    { question: 'ဘောက်ချာအခြေအနေကို တိကျစွာ ဘာကြောင့်ပြောင်းသင့်သလဲ?', choices: ['ဝင်ငွေနှင့် ငွေပေးချေမှုမှတ်တမ်း ယုံကြည်ရရန်', 'ပစ္စည်းအမည်ပြောင်းရန်', 'အမြဲတမ်း စတော့တိုးရန်'], answer: 0, note: 'တိကျသော Status သည် မရသေးသောအရောင်းနှင့် အမှန်တကယ်ရရှိသောငွေကို ခွဲခြားပေးသည်။' },
    { question: 'ရောင်းဈေးသတ်မှတ်ရာတွင် ဘာတွေကို ထည့်စဉ်းစားသင့်သလဲ?', choices: ['ကုန်ကျစရိတ်၊ ဝယ်ယူသူတန်ဖိုး၊ ဈေးကွက်နှင့် လိုချင်သောအမြတ်နှုန်း', 'အခြေအနေတိုင်းတွင် ကုန်ကျစရိတ်တစ်ခုတည်း', 'ကျပန်းနံပါတ်'], answer: 0, note: 'ကောင်းသောဈေးနှုန်းသည် ကုန်ကျစရိတ်၊ တန်ဖိုး၊ ပြိုင်ဘက်နှင့် အမြတ်နှုန်းကို မျှတစေသည်။' },
    { question: 'ပေးသွင်းသူများကို ဘာတွေနှိုင်းယှဉ်သင့်သလဲ?', choices: ['ဈေး၊ အရည်အသွေး၊ ယုံကြည်ရမှုနှင့် စည်းကမ်းချက်', 'လိုဂိုအရောင်သာ', 'Follower အရေအတွက်သာ'], answer: 0, note: 'ဈေးအသက်သာဆုံးဖြစ်သော်လည်း အရည်အသွေး သို့မဟုတ် ပို့ဆောင်မှုမယုံကြည်ရပါက အကောင်းဆုံးမဟုတ်နိုင်ပါ။' },
    { question: 'Marketing ROI က ဘာကိုတိုင်းတာပေးသလဲ?', choices: ['Marketing ကုန်ကျစရိတ်မှ ရရှိသောပြန်လာမှု', 'ပစ္စည်းအလေးချိန်', 'ဝန်ထမ်းတက်ရောက်မှု'], answer: 0, note: 'Marketing ROI သည် Campaign ကုန်ကျစရိတ်နှင့် ဖန်တီးပေးသောတန်ဖိုးကို နှိုင်းယှဉ်ပေးသည်။' },
    { question: 'ပြန်လည်ဝယ်ယူသူများ ဘာကြောင့်တန်ဖိုးရှိသလဲ?', choices: ['ပုံမှန်ဝင်ငွေနှင့် အခြားသူညွှန်းပေးမှု ရနိုင်သောကြောင့်', 'ဝန်ဆောင်မှုလုံးဝမလိုသောကြောင့်', 'ပစ္စည်းအားလုံး အမြဲဝယ်သောကြောင့်'], answer: 0, note: 'ပြန်လည်ဝယ်ယူသူများက ဝင်ငွေခန့်မှန်းရလွယ်စေပြီး အခြားသူများကို ဆိုင်အားညွှန်းပေးနိုင်သည်။' },
    { question: 'စတော့ကို လက်တွေ့ရေတွက်ခြင်း ဘာကြောင့်လုပ်သင့်သလဲ?', choices: ['စနစ်မှတ်တမ်းနှင့် လက်တွေ့စတော့ကို နှိုင်းယှဉ်ရန်', 'ငွေကြေးအမျိုးအစားပြောင်းရန်', 'ဝယ်ယူသူအကောင့်ဖန်တီးရန်'], answer: 0, note: 'လက်တွေ့ရေတွက်ခြင်းက ပျက်စီးမှု၊ ပျောက်ဆုံးမှုနှင့် မှတ်တမ်းအမှားကို ဖော်ထုတ်ပေးသည်။' },
    { question: 'ဒေတာ Backup အတွက် ကောင်းသောအလေ့အကျင့်က ဘာလဲ?', choices: ['လုံခြုံပြီး ပြန်ယူစမ်းသပ်ထားသော Backup ထားရန်', 'မစမ်းသပ်ထားသော Copy တစ်ခုသာထားရန်', 'Password ကို လူတိုင်းနှင့်မျှဝေရန်'], answer: 0, note: 'Backup သည် လုံခြုံပြီး အမှန်တကယ် ပြန်လည်ရယူနိုင်မှ အသုံးဝင်ပါသည်။' },
    { question: 'သံသယဖြစ်ဖွယ် Login link ရလျှင် ဘာလုပ်သင့်သလဲ?', choices: ['မဖွင့်ဘဲ တရားဝင်ဝဘ်ဆိုက်မှ စစ်ဆေးရန်', 'Password ချက်ချင်းထည့်ရန်', 'ဝယ်ယူသူများထံ ပို့ရန်'], answer: 0, note: 'Phishing link များက အကောင့်အချက်အလက် ခိုးယူနိုင်သောကြောင့် သိထားသောတရားဝင်လိပ်စာကို သုံးပါ။' },
    { question: 'ရာသီအလိုက်လိုအပ်ချက်အတွက် ဘယ်လိုပြင်ဆင်သင့်သလဲ?', choices: ['ယခင်အရောင်းနှင့် ပေးသွင်းသူပို့ဆောင်ချိန်ကို ကြည့်ရန်', 'ကျပန်းမှာယူရန်', 'စတော့ကို လျစ်လျူရှုရန်'], answer: 0, note: 'ယခင်လိုအပ်ချက်နှင့် ပို့ဆောင်ချိန်က ပိုမိုလုံခြုံသော ရာသီအလိုက်ဝယ်ယူမှုကို ကူညီပေးသည်။' },
    { question: 'အသုံးဝင်သော Upselling ဆိုသည်မှာ ဘာလဲ?', choices: ['လိုအပ်ချက်နှင့်ကိုက်ညီသော တန်ဖိုးပိုမြင့်သည့်ရွေးချယ်မှု အကြံပြုခြင်း', 'မလိုချင်သောပစ္စည်း အတင်းရောင်းခြင်း', 'မူလဈေးကို ဖျောက်ခြင်း'], answer: 0, note: 'ရိုးသားသော Upselling သည် ဝယ်ယူသူလိုအပ်ချက်နှင့် ပိုကိုက်ညီသောရွေးချယ်မှုကို ကူညီပေးသည်။' },
    { question: 'ဝယ်ယူသူ Feedback ကို ဘယ်လိုသုံးသင့်သလဲ?', choices: ['ထပ်တလဲလဲပေါ်သောအချက်များရှာပြီး ဦးစားပေးပြင်ဆင်ရန်', 'Comment တိုင်းကို မစဉ်းစားဘဲ လိုက်လုပ်ရန်', 'လုံးဝမမှတ်ရန်'], answer: 0, note: 'ထပ်တလဲလဲတွေ့ရသော Feedback သည် တစ်ဦးတည်း၏မှတ်ချက်ထက် ပိုခိုင်မာသောအထောက်အထားဖြစ်သည်။' },
    { question: 'မည်သည့်အရာက ပုံမှန်အားဖြင့် ပုံသေကုန်ကျစရိတ်ဖြစ်သလဲ?', choices: ['လစဉ်ဆိုင်ငှားခ', 'ရောင်းသည့်ပစ္စည်းတစ်ခုချင်း၏ ထုပ်ပိုးခ', 'ကုန်ပစ္စည်းဝယ်ဈေး'], answer: 0, note: 'ပုံသေကုန်ကျစရိတ်သည် အရောင်းအရေအတွက်ပြောင်းသော်လည်း အများအားဖြင့် ဆင်တူနေသည်။' },
    { question: 'ဝင်ငွေနှင့် အမြတ် ဘာကွာသလဲ?', choices: ['အမြတ်သည် ဝင်ငွေမှ ကုန်ကျစရိတ်နုတ်ပြီး ကျန်သည့်ပမာဏ', 'နှစ်ခုအမြဲတူသည်', 'ဝင်ငွေသည် အမြတ်ထက် အမြဲနည်းသည်'], answer: 0, note: 'ဝင်ငွေသည် အရောင်းမှရသည့်ငွေဖြစ်ပြီး အမြတ်သည် သက်ဆိုင်ရာကုန်ကျစရိတ်များ နုတ်ပြီးကျန်သည့်ပမာဏဖြစ်သည်။' },
  ],
};

export function shuffledBusinessQuiz(language: Language) {
  return [...questionBank[language]].sort(() => Math.random() - 0.5);
}
