import { ArrowRight, Bot, Check, KeyRound, LockKeyhole, Search, ShieldCheck, Sparkles, Store, UserCheck } from 'lucide-react';
import type { LandingAuthMode } from '@/pages/LandingPage';
import climbioLogo from '@/assets/branding/climbio-logo.png';
import { LandingButtonLabel } from '@/components/landing/LandingButtonLabel';

export function AISection() {
  return <section id="ai" className="landing-section overflow-hidden bg-gradient-to-br from-[#2b1760] via-[#2f195f] to-[#1d123c] py-24 text-white dark:from-[#0b0e19] dark:via-[#0b0e19] dark:to-[#0b0e19]"><div className="mx-auto grid max-w-7xl gap-12 px-5 sm:px-8 lg:grid-cols-[0.85fr_1.15fr] lg:items-center"><div><p className="text-xs font-black uppercase tracking-[0.18em] text-violet-200 dark:text-violet-300">AI business intelligence</p><h2 className="mt-4 text-3xl font-black leading-tight tracking-[-0.035em] sm:text-5xl">Your data tells a story.<br /><span className="text-violet-200 dark:text-violet-300">Climbio helps you understand it.</span></h2><p className="mt-6 text-lg leading-8 text-violet-100/75 dark:text-slate-400">Climbio&apos;s AI tools use your sales and inventory context to surface practical insights and answer business questions.</p><div className="mt-8 flex items-center gap-3 text-sm text-violet-100/80 dark:text-slate-300"><Sparkles className="size-5 text-violet-200 dark:text-violet-300" /> Based on your current Climbio records</div></div>
    <div className="rounded-2xl border border-violet-400/20 bg-gradient-to-br from-violet-500/[0.10] to-transparent p-4 shadow-[0_30px_80px_rgba(0,0,0,0.30)] sm:p-7"><div className="ml-auto max-w-[85%] rounded-2xl rounded-br-sm bg-violet-600 px-4 py-3 text-sm font-medium">What should I restock this week?</div><div className="mt-4 rounded-2xl rounded-bl-sm border border-white/10 bg-white/[0.05] p-5"><div className="flex items-center gap-2 text-xs font-black uppercase tracking-wider text-violet-300"><Bot className="size-4" /> Climbio AI</div><p className="mt-4 text-sm leading-7 text-slate-300">Based on recent sales and current stock, these products need attention:</p><div className="mt-5 space-y-3">{[['High priority', 'Restock Product A', 'text-red-300 bg-red-400/10'], ['Opportunity', 'Product B has strong sales momentum', 'text-emerald-300 bg-emerald-400/10'], ['Watch', 'Product C stock is moving slowly', 'text-amber-300 bg-amber-400/10']].map(([label, text, tone]) => <div key={label} className="flex items-start gap-3 rounded-xl border border-white/10 bg-black/10 p-3"><span className={`shrink-0 rounded-full px-2 py-1 text-[10px] font-black ${tone}`}>{label}</span><p className="pt-0.5 text-sm text-slate-300">{text}</p></div>)}</div></div></div>
  </div></section>;
}

export function StorefrontSection() {
  return <section className="bg-[#faf9ff] py-24 dark:bg-[#080b16]"><div className="mx-auto grid max-w-7xl gap-12 px-5 sm:px-8 lg:grid-cols-[1.1fr_0.9fr] lg:items-center"><StorePreview /><div><p className="text-xs font-black uppercase tracking-[0.18em] text-violet-600 dark:text-violet-300">Public storefront</p><h2 className="mt-4 text-3xl font-black leading-tight tracking-[-0.035em] text-slate-950 dark:text-white sm:text-5xl">Your products deserve more than a social media post.</h2><p className="mt-6 text-lg leading-8 text-slate-600 dark:text-slate-400">Approved shops can publish a public storefront where customers can browse active products without creating an account.</p><div className="mt-8 grid gap-3">{['Shareable shop link', 'Product browsing', 'Active inventory visibility', 'Customer-friendly interface'].map((item) => <div key={item} className="flex items-center gap-3 text-sm font-semibold text-slate-700 dark:text-slate-300"><span className="grid size-6 place-items-center rounded-full bg-emerald-100 text-emerald-700 dark:bg-emerald-400/10 dark:text-emerald-300"><Check className="size-3.5" /></span>{item}</div>)}</div></div></div></section>;
}

function StorePreview() {
  return <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-[0_28px_80px_rgba(30,20,70,0.15)] dark:border-white/10 dark:bg-[#0d1120]"><div className="flex items-center justify-between border-b border-slate-100 px-5 py-4 dark:border-white/10"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-violet-600 text-white"><Store className="size-5" /></span><div><p className="font-black dark:text-white">Mingalar Goods</p><p className="text-[10px] text-slate-500">Public product catalog</p></div></div><span className="text-xs font-semibold text-violet-600">Contact shop</span></div><div className="p-5"><div className="flex items-center gap-2 rounded-xl bg-slate-100 px-3 py-2.5 text-xs text-slate-400 dark:bg-white/[0.05]"><Search className="size-4" /> Search products</div><div className="mt-4 flex gap-2 overflow-hidden">{['All', 'Apparel', 'Accessories', 'Home'].map((item, index) => <span key={item} className={`shrink-0 rounded-full px-3 py-1.5 text-[10px] font-bold ${index === 0 ? 'bg-violet-600 text-white' : 'bg-slate-100 text-slate-500 dark:bg-white/5'}`}>{item}</span>)}</div><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-3">{['Classic Tee', 'Canvas Tote', 'Ceramic Mug', 'Notebook Set', 'Daily Cap', 'Desk Tray'].map((name, index) => <div key={name} className="rounded-xl border border-slate-100 p-2 dark:border-white/10"><div className={`aspect-[4/3] rounded-lg ${['bg-violet-100', 'bg-amber-100', 'bg-emerald-100', 'bg-blue-100', 'bg-rose-100', 'bg-orange-100'][index]}`} /><p className="mt-2 truncate text-xs font-bold dark:text-white">{name}</p><p className="mt-1 text-[10px] text-violet-600">View details</p></div>)}</div></div></div>;
}

const security = [[KeyRound, 'Secure authentication', 'Protected account sessions and securely stored passwords.'], [UserCheck, 'Role-based access', 'Different users only access the parts of the platform they are allowed to use.'], [ShieldCheck, 'Approval controls', 'Shop-owner access follows the platform review process.'], [LockKeyhole, 'Shop-level isolation', 'Business records remain associated with their own shop workspace.']];
export function SecuritySection() {
  return <section id="security" className="landing-section bg-white py-24 dark:bg-[#0b0e19]"><div className="mx-auto max-w-7xl px-5 sm:px-8"><div className="grid gap-12 lg:grid-cols-[0.65fr_1.35fr]"><div><p className="text-xs font-black uppercase tracking-[0.18em] text-violet-600 dark:text-violet-300">Trust by design</p><h2 className="mt-4 text-3xl font-black tracking-[-0.035em] text-slate-950 dark:text-white sm:text-5xl">Built around your business data.</h2><p className="mt-5 leading-7 text-slate-600 dark:text-slate-400">Practical protections help keep each business workspace appropriately controlled.</p></div><div className="divide-y divide-slate-200 border-y border-slate-200 dark:divide-white/10 dark:border-white/10">{security.map(([Icon, title, description]) => { const SecurityIcon = Icon as typeof KeyRound; return <div key={String(title)} className="grid gap-3 py-6 sm:grid-cols-[48px_180px_1fr] sm:items-center"><span className="grid size-10 place-items-center rounded-xl bg-violet-100 text-violet-700 dark:bg-violet-400/10 dark:text-violet-300"><SecurityIcon className="size-5" /></span><h3 className="font-black text-slate-950 dark:text-white">{String(title)}</h3><p className="text-sm leading-6 text-slate-600 dark:text-slate-400">{String(description)}</p></div>; })}</div></div></div></section>;
}

export function FinalCTA({ onOpenAuth }: { onOpenAuth: (mode: LandingAuthMode) => void }) {
  return <section className="bg-white px-5 py-16 dark:bg-[#0b0e19] sm:px-8 sm:py-20"><div className="relative mx-auto max-w-7xl overflow-hidden rounded-3xl border border-violet-400/20 bg-gradient-to-br from-[#321b6b] via-[#291653] to-[#1f123e] px-6 py-16 text-center text-white dark:from-[#080b16] dark:via-[#080b16] dark:to-[#080b16] sm:px-10 sm:py-20"><div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_50%_120%,rgba(167,139,250,0.30),transparent_48%)]" /><div className="relative mx-auto max-w-3xl"><h2 className="text-3xl font-black leading-tight tracking-[-0.035em] sm:text-5xl">Your business is already moving.<br />Give it a better system.</h2><p className="mx-auto mt-5 max-w-2xl text-lg leading-8 text-violet-100/75 dark:text-slate-400">Bring products, invoices, sales insights, your public store, and AI guidance into one Climbio workspace.</p><div className="mt-8 flex flex-col justify-center gap-3 sm:flex-row"><button type="button" onClick={() => onOpenAuth('signup')} className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-violet-500 px-6 font-bold text-white hover:bg-violet-400 dark:bg-violet-600 dark:hover:bg-violet-500"><LandingButtonLabel>Start your workspace</LandingButtonLabel><ArrowRight className="size-4" /></button><button type="button" onClick={() => onOpenAuth('login')} className="inline-flex min-h-12 items-center justify-center rounded-xl border border-white/20 px-6 font-bold text-white hover:bg-white/[0.08]"><LandingButtonLabel>Sign in</LandingButtonLabel></button></div></div></div></section>;
}

export function LandingFooter({ onOpenAuth }: { onOpenAuth: (mode: LandingAuthMode) => void }) {
  return <footer className="border-t border-slate-200 bg-white py-12 dark:border-white/10 dark:bg-[#080b16]"><div className="mx-auto grid max-w-7xl gap-10 px-5 sm:grid-cols-2 sm:px-8 lg:grid-cols-[1.5fr_1fr_1fr]"><div><a href="/#top" className="inline-flex rounded-lg" aria-label="Climbio home"><img src={climbioLogo} alt="Climbio" className="h-11 w-auto dark:brightness-0 dark:invert" /></a><p className="mt-3 text-sm text-slate-500">Smart business tools for growing SMEs.</p></div><FooterGroup title="Explore" links={[['Product', 'product'], ['Workflow', 'workflow'], ['AI', 'ai'], ['Security', 'security']]} /><div><h2 className="text-xs font-black uppercase tracking-wider dark:text-white">Account</h2><div className="mt-4 grid justify-items-start gap-3 text-sm text-slate-500"><button type="button" onClick={() => onOpenAuth('login')} className="hover:text-violet-600">Sign in</button><button type="button" onClick={() => onOpenAuth('signup')} className="hover:text-violet-600">Create account</button></div></div></div><div className="mx-auto mt-10 max-w-7xl border-t border-slate-100 px-5 pt-6 text-sm text-slate-400 dark:border-white/10 sm:px-8">© 2026 Climbio</div></footer>;
}

function FooterGroup({ title, links }: { title: string; links: string[][] }) { return <div><h2 className="text-xs font-black uppercase tracking-wider dark:text-white">{title}</h2><div className="mt-4 grid gap-3 text-sm text-slate-500">{links.map(([label, id]) => <a key={id} href={`/#${id}`} className="hover:text-violet-600">{label}</a>)}</div></div>; }
