import { ArrowRight, BarChart3, Bot, Boxes, Check, CircleDollarSign, FileText, LayoutDashboard, MessageSquareText, Package, ReceiptText, Settings, Store } from 'lucide-react';
import type { LandingAuthMode } from '@/pages/LandingPage';
import { LandingButtonLabel, landingIconTextFrameClass } from '@/components/landing/LandingButtonLabel';

const sidebar = [[LayoutDashboard, 'Overview'], [Package, 'Products'], [ReceiptText, 'Invoices'], [Store, 'Store'], [Bot, 'AI Advisor'], [MessageSquareText, 'AI Chat'], [Settings, 'Settings']];

export function HeroSection({ onOpenAuth }: { onOpenAuth: (mode: LandingAuthMode) => void }) {
  return <section id="top" className="landing-section relative overflow-hidden bg-[#faf9ff] pb-20 pt-32 dark:bg-[#080b16] sm:pt-36 lg:pb-28">
    <div className="pointer-events-none absolute inset-x-0 top-0 mx-auto h-[620px] max-w-6xl bg-[radial-gradient(ellipse_at_top,rgba(109,40,217,0.16),transparent_65%)] dark:bg-[radial-gradient(ellipse_at_top,rgba(124,58,237,0.20),transparent_65%)]" />
    <div className="relative mx-auto max-w-7xl px-5 sm:px-8">
      <div className="mx-auto max-w-4xl text-center">
        <div className="inline-flex items-center gap-2 rounded-full border border-violet-200/80 bg-white/80 px-3.5 py-1.5 text-xs font-bold tracking-[0.12em] text-violet-700 shadow-sm dark:border-violet-400/20 dark:bg-white/5 dark:text-violet-300"><span className="size-1.5 rounded-full bg-emerald-500" /> SMARTER TOOLS FOR GROWING SHOPS</div>
        <h1 className="mt-7 text-[clamp(2.7rem,7vw,4.8rem)] font-black leading-[1.02] tracking-[-0.055em] text-slate-950 dark:text-white">One workspace to run<br />your <span className="bg-gradient-to-r from-violet-600 via-purple-600 to-fuchsia-500 bg-clip-text text-transparent">whole business.</span></h1>
        <p className="mx-auto mt-6 max-w-3xl text-base leading-7 text-slate-600 dark:text-slate-300 sm:text-lg sm:leading-8">Manage products, inventory, invoices, sales, your public store, and AI-powered business guidance without switching between multiple tools.</p>
        <div className="mt-8 flex flex-col justify-center gap-3 sm:flex-row"><button type="button" onClick={() => onOpenAuth('signup')} className="inline-flex min-h-[52px] items-center justify-center gap-2 rounded-xl border border-violet-600 bg-violet-600 px-7 text-base font-bold text-white shadow-[0_12px_26px_rgba(109,40,217,0.24)] transition hover:border-violet-700 hover:bg-violet-700 motion-safe:hover:-translate-y-0.5 sm:min-w-[250px]"><LandingButtonLabel>Start your workspace</LandingButtonLabel><span className={landingIconTextFrameClass} aria-hidden="true"><ArrowRight className="block size-4" /></span></button><a href="/#workflow" className="inline-flex min-h-[52px] items-center justify-center rounded-xl border border-slate-300 bg-white px-7 text-base font-bold text-slate-800 shadow-sm transition hover:border-violet-400 hover:bg-violet-50 hover:text-violet-700 dark:border-white/15 dark:bg-white/[0.06] dark:text-white dark:hover:border-violet-400 dark:hover:bg-white/[0.10] sm:min-w-[230px]"><LandingButtonLabel>Explore how it works</LandingButtonLabel></a></div>
        <div className="mt-7 flex flex-wrap justify-center gap-x-6 gap-y-2 text-sm text-slate-500 dark:text-slate-400">{['Secure setup', 'Admin-reviewed shops', 'Built for growing SMEs'].map((item) => <span key={item} className="inline-flex items-center gap-1.5"><Check className="size-4 text-emerald-500" />{item}</span>)}</div>
      </div>
      <WorkspacePreview />
    </div>
  </section>;
}

function WorkspacePreview() {
  return <div className="relative mx-auto mt-16 max-w-6xl lg:mt-20">
    <div className="absolute inset-x-[10%] bottom-0 h-32 bg-violet-600/20 blur-3xl" />
    <div className="relative overflow-hidden rounded-2xl border border-slate-200/80 bg-white shadow-[0_35px_100px_rgba(30,20,70,0.20)] dark:border-violet-300/15 dark:bg-[#0d1120]">
      <div className="flex h-10 items-center gap-1.5 border-b border-slate-200 bg-slate-50 px-4 dark:border-white/10 dark:bg-white/[0.03]"><span className="size-2.5 rounded-full bg-red-400" /><span className="size-2.5 rounded-full bg-amber-400" /><span className="size-2.5 rounded-full bg-emerald-400" /><span className="mx-auto h-5 w-48 rounded-md bg-slate-200/70 dark:bg-white/[0.06]" /></div>
      <div className="grid min-h-[500px] grid-cols-[68px_1fr] md:grid-cols-[190px_1fr]">
        <aside className="border-r border-violet-300/20 bg-[#2b1760] p-3 text-violet-200 dark:border-white/10 dark:bg-slate-950 dark:text-slate-400"><div className="mb-6 hidden text-sm font-black text-white md:block">Climbio workspace</div><div className="space-y-1">{sidebar.map(([Icon, label], index) => { const SideIcon = Icon as typeof Package; return <div key={String(label)} className={`flex items-center gap-3 rounded-lg px-3 py-2.5 text-xs font-semibold ${index === 0 ? 'bg-violet-600 text-white' : ''}`}><span className={landingIconTextFrameClass} aria-hidden="true"><SideIcon className="block size-4 shrink-0" /></span><span className="hidden leading-none md:block">{String(label)}</span></div>; })}</div></aside>
        <div className="min-w-0 bg-slate-50 p-4 dark:bg-[#090d19] sm:p-6 lg:p-8"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-violet-600">Business overview</p><h2 className="mt-1 text-xl font-black dark:text-white sm:text-2xl">Good morning, Shop Owner</h2></div><span className="hidden rounded-lg border border-slate-200 bg-white px-3 py-2 text-xs font-semibold text-slate-500 dark:border-white/10 dark:bg-white/5 sm:block">Demo workspace</span></div>
          <div className="mt-6 grid grid-cols-3 gap-2 sm:gap-4">{[[CircleDollarSign, 'Revenue', '1.28M MMK'], [Boxes, 'Products', '128'], [FileText, 'Invoices', '36']].map(([Icon, label, value]) => { const MetricIcon = Icon as typeof Boxes; return <div key={String(label)} className="rounded-xl border border-slate-200 bg-white p-3 dark:border-white/10 dark:bg-white/[0.04] sm:p-4"><MetricIcon className="size-4 text-violet-600" /><p className="mt-3 truncate text-[10px] text-slate-500 sm:text-xs">{String(label)}</p><p className="mt-1 truncate text-sm font-black dark:text-white sm:text-lg">{String(value)}</p></div>; })}</div>
          <div className="mt-4 grid gap-4 lg:grid-cols-[1.45fr_0.55fr]"><div className="rounded-xl border border-slate-200 bg-white p-4 dark:border-white/10 dark:bg-white/[0.04]"><div className="flex justify-between"><p className="text-sm font-bold dark:text-white">Sales performance</p><span className="text-xs font-bold text-emerald-500">+18.4%</span></div><div className="mt-5 flex h-40 items-end gap-2" aria-hidden="true">{[38, 52, 46, 67, 58, 79, 71, 94, 82, 100].map((height, index) => <span key={index} className="flex-1 rounded-t bg-gradient-to-t from-violet-700 to-violet-400" style={{ height: `${height}%`, opacity: 0.48 + index * 0.045 }} />)}</div></div><div className="space-y-4"><div className="rounded-xl border border-amber-200 bg-amber-50 p-4 dark:border-amber-400/20 dark:bg-amber-400/10"><p className="text-xs font-bold text-amber-700 dark:text-amber-300">Low Stock</p><p className="mt-2 text-2xl font-black dark:text-white">3</p><p className="text-xs text-slate-500">products need attention</p></div><div className="rounded-xl border border-violet-200 bg-violet-50 p-4 dark:border-violet-400/20 dark:bg-violet-400/10"><div className="flex gap-2"><Bot className="size-4 text-violet-600" /><p className="text-xs font-bold text-violet-700 dark:text-violet-300">AI Recommendation</p></div><p className="mt-2 text-xs leading-5 text-slate-600 dark:text-slate-300">Restock your best-selling item this week.</p></div></div></div>
        </div>
      </div>
    </div>
    <div className="absolute -left-5 top-1/3 hidden w-52 rounded-xl border border-amber-200 bg-white p-4 shadow-xl dark:border-amber-400/20 dark:bg-[#111626] lg:block"><p className="text-xs font-bold text-amber-600">Low stock</p><p className="mt-1 text-sm font-semibold dark:text-white">3 products need attention</p></div>
    <div className="absolute -right-5 top-24 hidden w-52 rounded-xl border border-emerald-200 bg-white p-4 shadow-xl dark:border-emerald-400/20 dark:bg-[#111626] lg:block"><p className="text-xs font-bold text-emerald-600">Invoice paid</p><p className="mt-1 text-sm font-semibold dark:text-white">INV-2026-0042</p></div>
  </div>;
}
