import { useState } from 'react';
import { ArrowDown, ArrowRight, BarChart3, Bot, Boxes, CheckCircle2, Package, ReceiptText, Store, TrendingUp, UsersRound } from 'lucide-react';

export function BusinessWorkflow() {
  const flow = [[Boxes, 'Products'], [Package, 'Inventory'], [ReceiptText, 'Invoice'], [TrendingUp, 'Sales'], [BarChart3, 'Dashboard'], [Bot, 'AI Insight']];
  return <section id="workflow" className="landing-section overflow-hidden bg-gradient-to-br from-[#2b1760] via-[#321b6b] to-[#201243] py-24 text-white dark:from-[#080b16] dark:via-[#080b16] dark:to-[#080b16]"><div className="mx-auto max-w-7xl px-5 sm:px-8"><div className="max-w-3xl"><p className="text-xs font-black uppercase tracking-[0.18em] text-violet-200 dark:text-violet-300">Connected workflow</p><h2 className="mt-4 text-3xl font-black tracking-[-0.035em] sm:text-5xl">Your business data should work together.</h2><p className="mt-5 text-lg leading-8 text-violet-100/75 dark:text-slate-400">Every product, invoice, and sale contributes to a clearer view of your business.</p></div>
    <div className="relative mt-14"><div className="hidden items-center justify-between lg:flex">{flow.map(([Icon, label], index) => { const FlowIcon = Icon as typeof Boxes; return <div key={String(label)} className="contents"><div className="relative z-10 flex w-32 flex-col items-center gap-3 text-center"><span className="grid size-14 place-items-center rounded-2xl border border-violet-400/25 bg-violet-400/10 text-violet-300 shadow-[0_0_30px_rgba(124,58,237,0.10)]"><FlowIcon className="size-6" /></span><span className="text-sm font-bold">{String(label)}</span></div>{index < flow.length - 1 && <div className="h-px flex-1 bg-gradient-to-r from-violet-500/60 to-violet-400/20"><ArrowRight className="ml-auto size-4 -translate-y-1/2 text-violet-400" /></div>}</div>; })}</div>
      <div className="grid gap-2 lg:hidden">{flow.map(([Icon, label], index) => { const FlowIcon = Icon as typeof Boxes; return <div key={String(label)} className="contents"><div className="flex items-center gap-3 rounded-xl border border-white/10 bg-white/[0.04] p-4"><FlowIcon className="size-5 text-violet-300" /><span className="font-bold">{String(label)}</span></div>{index < flow.length - 1 && <ArrowDown className="mx-auto size-4 text-violet-400" />}</div>; })}</div>
      <div className="mx-auto mt-12 grid max-w-lg grid-cols-[1fr_auto_1fr_auto_1fr] items-center gap-2 rounded-2xl border border-white/10 bg-white/[0.04] p-4 text-center text-xs font-bold sm:text-sm"><span>Products</span><ArrowRight className="size-4 text-violet-400" /><span>Public Store</span><ArrowRight className="size-4 text-violet-400" /><span className="text-emerald-300">Customers</span></div>
    </div>
  </div></section>;
}

type Module = 'dashboard' | 'inventory' | 'invoices' | 'store';
const modules: Array<{ id: Module; label: string; description: string }> = [
  { id: 'dashboard', label: 'Dashboard', description: 'See revenue, sales trends, and business health at a glance.' },
  { id: 'inventory', label: 'Inventory', description: 'Organize products, categories, pricing, and stock.' },
  { id: 'invoices', label: 'Invoices', description: 'Create professional invoices and follow their status.' },
  { id: 'store', label: 'Public Store', description: 'Present active products in a customer-friendly catalog.' },
];

export function ProductShowcase() {
  const [selected, setSelected] = useState<Module>('dashboard');
  const active = modules.find((module) => module.id === selected)!;
  return <section className="bg-[#faf9ff] py-24 dark:bg-[#0b0e19]"><div className="mx-auto max-w-7xl px-5 sm:px-8"><div className="grid gap-10 lg:grid-cols-[300px_1fr] lg:items-center"><div><p className="text-xs font-black uppercase tracking-[0.18em] text-violet-600 dark:text-violet-300">Explore the product</p><h2 className="mt-4 text-3xl font-black tracking-[-0.035em] dark:text-white sm:text-4xl">Built around the way your shop works.</h2><p className="mt-4 leading-7 text-slate-600 dark:text-slate-400">Choose a module to see how Climbio keeps daily work focused and connected.</p><div className="mt-8 flex gap-2 overflow-x-auto pb-2 lg:grid" role="tablist" aria-label="Climbio modules">{modules.map((module) => <button key={module.id} type="button" role="tab" aria-selected={selected === module.id} aria-controls="product-showcase-panel" onClick={() => setSelected(module.id)} className={`tab-control min-w-max flex-col items-start rounded-xl border px-4 py-3 text-left transition lg:min-w-0 ${selected === module.id ? 'border-violet-500 bg-violet-600 text-white shadow-lg shadow-violet-600/15' : 'border-slate-200 bg-white text-slate-600 hover:border-violet-300 dark:border-white/10 dark:bg-white/[0.03] dark:text-slate-300'}`}><span className="font-bold">{module.label}</span><span className={`mt-1 hidden text-xs leading-5 lg:block ${selected === module.id ? 'text-violet-100' : 'text-slate-400'}`}>{module.description}</span></button>)}</div></div><div id="product-showcase-panel" role="tabpanel" className="min-h-[430px] overflow-hidden rounded-2xl border border-slate-200 bg-white p-4 shadow-[0_24px_70px_rgba(30,20,70,0.12)] dark:border-white/10 dark:bg-[#0d1120] sm:p-7"><div key={selected} className="motion-safe:animate-[fadeIn_240ms_ease-out]"><Preview module={selected} /></div></div></div></div></section>;
}

function Preview({ module }: { module: Module }) {
  if (module === 'inventory') return <div><PreviewHeader icon={Boxes} title="Products & Inventory" subtitle="128 products across 8 categories" /><div className="mt-7 overflow-hidden rounded-xl border border-slate-200 dark:border-white/10">{[['Classic Tee', 'Apparel', '24', '32,000'], ['Canvas Bag', 'Accessories', '5', '28,000'], ['Ceramic Mug', 'Home', '0', '18,500'], ['Notebook Set', 'Stationery', '42', '12,000']].map(([name, category, stock, price]) => <div key={name} className="grid grid-cols-[1fr_70px] gap-3 border-b border-slate-100 p-4 last:border-0 dark:border-white/10 sm:grid-cols-[1fr_120px_80px_100px]"><span className="font-bold dark:text-white">{name}</span><span className="hidden text-sm text-slate-500 sm:block">{category}</span><span className={Number(stock) <= 5 ? 'text-sm font-bold text-amber-500' : 'text-sm text-slate-500'}>{stock} stock</span><span className="hidden text-right text-sm font-semibold dark:text-slate-300 sm:block">{price}</span></div>)}</div></div>;
  if (module === 'invoices') return <div><PreviewHeader icon={ReceiptText} title="Invoice Management" subtitle="Track every invoice from draft to paid" /><div className="mt-7 space-y-3">{[['INV-2026-0042', 'Golden Corner Shop', '185,000 MMK', 'PAID'], ['INV-2026-0041', 'May Online Store', '92,500 MMK', 'SENT'], ['INV-2026-0040', 'Thiri Retail', '48,000 MMK', 'DRAFT']].map(([number, customer, total, status]) => <div key={number} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-slate-200 p-4 dark:border-white/10"><div><p className="font-bold dark:text-white">{number}</p><p className="mt-1 text-xs text-slate-500">{customer}</p></div><p className="font-semibold dark:text-slate-200">{total}</p><span className={`rounded-full px-2.5 py-1 text-[10px] font-black ${status === 'PAID' ? 'bg-emerald-100 text-emerald-700' : status === 'SENT' ? 'bg-blue-100 text-blue-700' : 'bg-slate-100 text-slate-600'}`}>{status}</span></div>)}</div></div>;
  if (module === 'store') return <div><PreviewHeader icon={Store} title="Mingalar Goods" subtitle="Public storefront preview" /><div className="mt-5 flex gap-2 overflow-x-auto">{['All', 'Apparel', 'Accessories', 'Home'].map((category, index) => <span key={category} className={`rounded-full px-3 py-1.5 text-xs font-semibold ${index === 0 ? 'bg-violet-600 text-white' : 'bg-slate-100 text-slate-500 dark:bg-white/5'}`}>{category}</span>)}</div><div className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-3">{['Classic Tee', 'Canvas Bag', 'Ceramic Mug'].map((name, index) => <div key={name} className="rounded-xl border border-slate-200 p-3 dark:border-white/10"><div className={`aspect-square rounded-lg ${['bg-violet-100', 'bg-amber-100', 'bg-emerald-100'][index]}`} /><p className="mt-3 font-bold dark:text-white">{name}</p><p className="mt-1 text-xs text-violet-600">{[32000, 28000, 18500][index].toLocaleString()} MMK</p></div>)}</div></div>;
  return <div><PreviewHeader icon={BarChart3} title="Business Dashboard" subtitle="Your shop performance in one clear view" /><div className="mt-7 grid grid-cols-3 gap-3">{[['Revenue', '1.28M'], ['Products', '128'], ['Invoices', '36']].map(([label, value]) => <div key={label} className="rounded-xl bg-slate-50 p-4 dark:bg-white/[0.04]"><p className="text-xs text-slate-500">{label}</p><p className="mt-2 text-xl font-black dark:text-white">{value}</p></div>)}</div><div className="mt-5 flex h-52 items-end gap-2 rounded-xl border border-slate-200 p-5 dark:border-white/10" aria-hidden="true">{[35, 58, 49, 72, 62, 88, 75, 100, 86].map((height, index) => <span key={index} className="flex-1 rounded-t bg-violet-500" style={{ height: `${height}%`, opacity: 0.4 + index * 0.06 }} />)}</div></div>;
}

function PreviewHeader({ icon: Icon, title, subtitle }: { icon: typeof Boxes; title: string; subtitle: string }) { return <div className="flex items-center gap-3"><span className="grid size-11 place-items-center rounded-xl bg-violet-100 text-violet-700 dark:bg-violet-400/10 dark:text-violet-300"><Icon className="size-5" /></span><div><h3 className="font-black dark:text-white">{title}</h3><p className="mt-0.5 text-xs text-slate-500">{subtitle}</p></div></div>; }

export function OnboardingTimeline() {
  const steps = [['01', 'Create account', 'Register as a shop owner.'], ['02', 'Submit your shop', 'Provide the basic information required for platform review.'], ['03', 'Admin review', 'Climbio reviews the application. If changes are requested, update and resubmit.'], ['04', 'Start managing', 'After approval, access inventory, invoices, storefront, dashboard, and AI tools.']];
  return <section className="bg-white py-24 dark:bg-[#080b16]"><div className="mx-auto max-w-7xl px-5 sm:px-8"><div className="mx-auto max-w-3xl text-center"><p className="text-xs font-black uppercase tracking-[0.18em] text-violet-600 dark:text-violet-300">Simple and secure onboarding</p><h2 className="mt-4 text-3xl font-black tracking-[-0.035em] dark:text-white sm:text-5xl">From signup to your business workspace.</h2></div><div className="relative mt-14 grid gap-7 lg:grid-cols-4"><div className="absolute left-[12%] right-[12%] top-5 hidden h-px bg-gradient-to-r from-violet-200 via-violet-500 to-violet-200 lg:block dark:from-violet-500/10 dark:via-violet-400/50 dark:to-violet-500/10" />{steps.map(([number, title, description]) => <article key={number} className="relative pl-14 lg:pl-0"><span className="absolute left-0 top-0 z-10 grid size-10 place-items-center rounded-full bg-violet-600 text-xs font-black text-white ring-8 ring-white dark:ring-[#080b16] lg:relative">{number}</span><h3 className="mt-1 font-black dark:text-white lg:mt-7">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600 dark:text-slate-400">{description}</p>{number === '03' && <div className="mt-3 inline-flex items-center gap-1.5 text-xs font-semibold text-amber-600"><CheckCircle2 className="size-3.5" /> Approval required</div>}</article>)}</div></div></section>;
}
