import { BarChart3, Bot, Boxes, MessageSquareText, ReceiptText, Store } from 'lucide-react';

const products = [['Classic Tee', '24', 'Apparel'], ['Canvas Bag', '5', 'Accessories'], ['Daily Mug', '0', 'Home']];

export function ProductBento() {
  return <section id="product" className="landing-section bg-white py-24 dark:bg-[#0b0e19]"><div className="mx-auto max-w-7xl px-5 sm:px-8"><div className="max-w-3xl"><p className="text-xs font-black uppercase tracking-[0.18em] text-violet-600 dark:text-violet-300">Climbio workspace</p><h2 className="mt-4 font-display text-3xl font-semibold leading-[1.08] tracking-[-0.035em] text-slate-950 dark:text-white sm:text-5xl">Everything your shop needs,<br />working together.</h2><p className="mt-5 text-lg leading-8 text-slate-600 dark:text-slate-400">No disconnected spreadsheets, invoice apps, product lists, and business tools.</p></div>
    <div className="mt-14 grid auto-rows-[minmax(190px,auto)] gap-4 md:grid-cols-6">
      <article className="group overflow-hidden rounded-2xl border border-slate-200 bg-slate-50 p-6 transition motion-safe:hover:-translate-y-1 hover:border-violet-300 dark:border-white/10 dark:bg-white/[0.035] md:col-span-4 md:row-span-2"><BentoTitle icon={Boxes} title="Inventory & Products" /><p className="mt-3 max-w-xl text-sm leading-6 text-slate-600 dark:text-slate-400">Manage products, categories, pricing, stock levels, and images from one organized inventory.</p><div className="mt-7 overflow-hidden rounded-xl border border-slate-200 bg-white dark:border-white/10 dark:bg-[#0d1120]"><div className="grid grid-cols-[1fr_70px_90px] border-b border-slate-100 px-4 py-2 text-[10px] font-bold uppercase tracking-wider text-slate-400 dark:border-white/10"><span>Product</span><span>Stock</span><span>Category</span></div>{products.map(([name, stock, category]) => <div key={name} className="grid grid-cols-[1fr_70px_90px] items-center border-b border-slate-100 px-4 py-3 text-xs last:border-0 dark:border-white/10"><span className="font-semibold dark:text-white">{name}</span><span className={stock === '0' ? 'font-bold text-red-500' : Number(stock) <= 5 ? 'font-bold text-amber-500' : 'text-slate-500'}>{stock}</span><span className="truncate rounded-full bg-violet-50 px-2 py-1 text-center text-[10px] text-violet-700 dark:bg-violet-400/10 dark:text-violet-300">{category}</span></div>)}</div></article>
      <article className="rounded-2xl border border-violet-500/20 bg-gradient-to-br from-[#432879] to-[#2b1760] p-6 text-white transition motion-safe:hover:-translate-y-1 dark:border-violet-400/15 dark:from-[#0d1120] dark:to-[#0d1120] md:col-span-2"><BentoTitle icon={ReceiptText} title="Invoices" dark /><p className="mt-3 text-sm leading-6 text-violet-100/75 dark:text-slate-400">Create professional invoices, track status, and generate PDF documents.</p><div className="mt-6 rounded-xl border border-white/10 bg-white/[0.08] p-4"><div className="flex justify-between"><span className="text-xs text-violet-100/70 dark:text-slate-400">INV-2026-0042</span><span className="rounded-full bg-emerald-400/15 px-2 py-1 text-[10px] font-bold text-emerald-200">PAID</span></div><p className="mt-5 text-xl font-black">185,000 MMK</p><p className="mt-1 text-xs text-violet-100/60 dark:text-slate-500">3 invoice items</p></div></article>
      <article className="rounded-2xl border border-slate-200 bg-white p-6 transition motion-safe:hover:-translate-y-1 dark:border-white/10 dark:bg-white/[0.035] md:col-span-2"><BentoTitle icon={BarChart3} title="Business Overview" /><p className="mt-3 text-sm leading-6 text-slate-600 dark:text-slate-400">See sales performance and key shop metrics without digging through spreadsheets.</p><div className="mt-5 flex h-16 items-end gap-1.5" aria-hidden="true">{[42, 68, 55, 80, 64, 96, 86].map((height, index) => <span key={index} className="flex-1 rounded-t bg-violet-500" style={{ height: `${height}%`, opacity: 0.35 + index * 0.08 }} />)}</div></article>
      <article className="overflow-hidden rounded-2xl border border-violet-200 bg-violet-50 p-6 transition motion-safe:hover:-translate-y-1 dark:border-violet-400/15 dark:bg-violet-500/[0.07] md:col-span-4"><BentoTitle icon={Store} title="Public Store" /><p className="mt-3 max-w-xl text-sm leading-6 text-slate-600 dark:text-slate-400">Turn your approved shop into a shareable public product catalog.</p><div className="mt-5 grid grid-cols-3 gap-2">{['Linen Shirt', 'Canvas Tote', 'Ceramic Mug'].map((name, index) => <div key={name} className="rounded-xl bg-white p-2 shadow-sm dark:bg-[#111626]"><div className={`aspect-[4/3] rounded-lg ${['bg-violet-100', 'bg-amber-100', 'bg-emerald-100'][index]}`} /><p className="mt-2 truncate text-[10px] font-bold dark:text-white sm:text-xs">{name}</p></div>)}</div></article>
      <article className="rounded-2xl border border-slate-200 bg-white p-6 transition motion-safe:hover:-translate-y-1 dark:border-white/10 dark:bg-white/[0.035] md:col-span-3"><BentoTitle icon={Bot} title="AI Advisor" /><p className="mt-3 text-sm leading-6 text-slate-600 dark:text-slate-400">Turn real shop data into practical recommendations.</p><div className="mt-5 rounded-xl border-l-2 border-violet-500 bg-slate-50 p-4 text-xs leading-5 text-slate-600 dark:bg-white/[0.04] dark:text-slate-300">Inventory alert: Canvas Bag is selling steadily and has only 5 units remaining.</div></article>
      <article className="rounded-2xl border border-violet-500/20 bg-gradient-to-br from-[#35205f] to-[#241443] p-6 text-white transition motion-safe:hover:-translate-y-1 dark:border-white/10 dark:from-slate-950 dark:to-slate-950 md:col-span-3"><BentoTitle icon={MessageSquareText} title="AI Chat" dark /><p className="mt-3 text-sm leading-6 text-violet-100/75 dark:text-slate-400">Ask questions about your business using your own shop context.</p><div className="mt-5 ml-auto w-fit max-w-[90%] rounded-xl rounded-br-sm bg-violet-500 px-4 py-2.5 text-xs">Which products should I restock?</div></article>
    </div>
  </div></section>;
}

function BentoTitle({ icon: Icon, title, dark = false }: { icon: typeof Boxes; title: string; dark?: boolean }) {
  return <div className="flex items-center gap-3"><span className={`grid size-9 place-items-center rounded-lg ${dark ? 'bg-white/10 text-violet-300' : 'bg-violet-100 text-violet-700 dark:bg-violet-400/10 dark:text-violet-300'}`}><Icon className="size-4" /></span><h3 className={`font-black ${dark ? 'text-white' : 'text-slate-950 dark:text-white'}`}>{title}</h3></div>;
}
